const USERS_ACTION_TYPES = {
  SEARCH_USERS_START: 'users/SEARCH_USERS_START',
  SEARCH_USERS_SUCCESS: 'users/SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILED: 'users/SEARCH_USERS_FAILED',
  GROUP_CHAT_USERS_SEARCH_START: 'users/GROUP_CHAT_USERS_SEARCH_START',
  GROUP_CHAT_USERS_SEARCH_SUCCESS: 'users/GROUP_CHAT_USERS_SEARCH_SUCCESS',
  GROUP_CHAT_USERS_SEARCH_FAILED: 'users/GROUP_CHAT_USERS_SEARCH_FAILED',
  CLEAR_GROUP_CHAT_USER: 'users/CLEAR_GROUP_CHAT_USER',
};

export default USERS_ACTION_TYPES;
