const USERS_ACTION_TYPES = {
  SEARCH_USERS_START: 'user/SEARCH_USERS_START',
  SEARCH_USERS_SUCCESS: 'user/SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILED: 'user/SEARCH_USERS_FAILED',
};

export default USERS_ACTION_TYPES;
