const CHAT_ACTION_TYPES = {
  GET_MY_CHATS_START: 'chat/GET_MY_CHATS_START',
  GET_MY_CHATS_SUCCESS: 'chat/GET_MY_CHATS_SUCCESS',
  GET_MY_CHATS_FAILED: 'chat/GET_MY_CHATS_FAILED',
  SET_SELECTED_USER: 'chat/SET_SELECTED_USER',
  ACCESS_CHAT_START: 'chat/ACCESS_CHAT_START',
  ACCESS_CHAT_SUCCESS: 'chat/ACCESS_CHAT_SUCCESS',
  ACCESS_CHAT_FAILED: 'chat/ACCESS_CHAT_FAILED',
  CREATE_GROUP_CHAT_START: 'chat/CREATE_GROUP_CHAT_START',
  CREATE_GROUP_CHAT_SUCCESS: 'chat/CREATE_GROUP_CHAT_SUCCESS',
  CREATE_GROUP_CHAT_FAILED: 'chat/CREATE_GROUP_CHAT_FAILED',
};

export default CHAT_ACTION_TYPES;
