const USER_ACTION_TYPES = {
  LOGIN_START: 'user/LOGIN_START',
  LOGIN_SUCCESS: 'user/LOGIN_SUCCESS',
  LOGIN_FAILED: 'user/LOGIN_FAILED',
  LOGOUT_START: 'user/LOGOUT_START',
  LOGOUT_SUCCESS: 'user/LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'user/LOGOUT_FAILED',
  SEARCH_USERS_START: 'user/SEARCH_USERS_START',
  SEARCH_USERS_SUCCESS: 'user/SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILED: 'user/SEARCH_USERS_FAILED',
};

export default USER_ACTION_TYPES;
