const MESSAGE_ACTION_TYPES = {
  GET_ALL_MESSAGES_START: 'message/GET_ALL_MESSAGES_START',
  GET_ALL_MESSAGES_SUCCESS: 'message/GET_ALL_MESSAGES_SUCCESS',
  GET_ALL_MESSAGES_FAILED: 'message/GET_ALL_MESSAGES_FAILED',
  SET_MESSAGES: 'message/SET_MESSAGES',
  SEND_MESSAGE_START: 'message/SEND_MESSAGE_START',
  SEND_MESSAGE_SUCCESS: 'message/SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILED: 'message/SEND_MESSAGE_FAILED',
};

export default MESSAGE_ACTION_TYPES;
